services:
  comfyui:
    image: comfyui-docker-build:runtime
    build:
      context: .
      target: runtime
    container_name: comfyui_container
    restart: unless-stopped
    init: true

    ports:
      - "127.0.0.1:8188:8188"

    environment:
      NVIDIA_VISIBLE_DEVICES: all

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    volumes:
      - ./data/models:/app/models
      - ./data/custom_nodes:/app/custom_nodes
      - ./data/output:/app/output
      - ./data/input:/app/input
      - ./data/user:/app/user
